MODEL:
  PRETRAIN_PATH_T: '/home/zubuntu/workspace/yzy/MambaPro/pths/ViT-B-16.pt' # 预训练权重
  TRANSFORMER_TYPE: 'ViT-B-16' # 骨干类型
  STRIDE_SIZE: [ 16, 16 ] # 步长
  SIE_CAMERA: True # 是否使用相机嵌入
  DIRECT: 1 # 直接
  SIE_COE: 1.0 # 相机嵌入系数
  ID_LOSS_WEIGHT: 0.25 # 分类损失权重
  TRIPLET_LOSS_WEIGHT: 1.0 # 三元组损失权重
  PROMPT: True # 是否使用提示
  ADAPTER: True # 是否使用适配器
  MAMBA: True # 是否使用Mamba
  FROZEN: True # 是否冻结
  
  # ========== 创新点配置：CLIP多尺度滑动窗口模块 ==========
  # 用户修改：在保持CLIP分支的基础上，添加多尺度滑动窗口配置
  # 功能：启用基于CLIP的多尺度特征提取机制
  # 🔥 测试控制：设置为False使用原始CLIP，设置为True使用多尺度滑动窗口
  USE_CLIP_MULTI_SCALE: False   # 启用CLIP多尺度滑动窗口特征提取
  CLIP_MULTI_SCALE_SCALES: [4, 8, 16]  # 滑动窗口尺度（4x4小窗口，8x8中窗口，16x16大窗口）
  
  # ========== 创新点配置：多尺度MoE特征融合模块 ==========
  # 用户修改：添加多尺度MoE特征融合配置，支持命令行开关控制
  # 功能：启用基于专家网络的多尺度特征动态融合机制
  # 🔥 测试控制：可通过--use_moe启用，--disable_moe禁用，或直接修改此配置
  USE_MULTI_SCALE_MOE: False    # 启用多尺度MoE特征融合模块
  MOE_SCALES: [4, 8, 16]        # MoE滑动窗口尺度（与多尺度滑动窗口保持一致）
  MOE_EXPERT_HIDDEN_DIM: 1024   # MoE专家网络隐藏层维度
  MOE_TEMPERATURE: 1.0          # MoE门控网络温度参数（控制权重分布尖锐程度）

INPUT:
  SIZE_TRAIN: [ 256, 128 ] # 训练尺寸
  SIZE_TEST: [ 256, 128 ] # 测试尺寸
  PROB: 0.5 # random horizontal flip # 随机水平翻转
  RE_PROB: 0.5 # random erasing # 随机擦除
  PADDING: 10 # 填充

DATALOADER:
  SAMPLER: 'softmax_triplet' # 采样器
  NUM_INSTANCE: 8 # 每个批次实例数 (提高采样多样性)
  NUM_WORKERS: 8 # 工作线程数

DATASETS:
  NAMES: ('RGBNT201') # 数据集名称
  ROOT_DIR: '/home/zubuntu/workspace/yzy/MambaPro/data/' # 数据集根目录

SOLVER:
  # 优化器设置
  OPTIMIZER_NAME: 'Adam' # 优化器名称
  BASE_LR: 0.0005 # 基础学习率 (论文baseline推荐值)
  WEIGHT_DECAY: 0.0005 # 权重衰减
  WEIGHT_DECAY_BIAS: 0.0005 # 偏置权重衰减
  MOMENTUM: 0.9 # 动量
  
  # 训练设置
  MAX_EPOCHS: 60 # 最大迭代数 (论文标准设置)
  IMS_PER_BATCH: 32 # 每个批次图像数 (提高训练稳定性)
  WARMUP_ITERS: 20 # 预热迭代数 (充分预热)
  WARMUP_METHOD: 'linear' # 预热方法
  WARMUP_FACTOR: 0.01 # 预热因子
  
  # 损失函数设置
  MARGIN: 0.3 # 三元组损失边界
  CENTER_LOSS_WEIGHT: 0.0005 # 中心损失权重
  CENTER_LR: 0.5 # 中心学习率
  
  # 学习率调度
  GAMMA: 0.1 # 衰减率
  STEPS: (30, 50) # 学习率衰减步数
  
  # 其他设置
  SEED: 42 # 随机种子 (确保可复现性)
  CHECKPOINT_PERIOD: 10 # 检查点保存周期
  LOG_PERIOD: 10 # 日志打印周期
  EVAL_PERIOD: 5 # 验证周期

TEST:
  IMS_PER_BATCH: 64 # 每个批次图像数 (测试时可以更大)
  RE_RANKING: 'no' # 是否重新排序
  WEIGHT: '/home/zubuntu/workspace/yzy/MambaPro/pths/MambaProbest.pth' # 权重路径
  NECK_FEAT: 'after' # 颈部特征 (使用after获得更好性能)
  FEAT_NORM: 'yes' # 特征归一化
  MISS: "nothing" # 缺失

# ========== 创新点实验输出目录 ==========
# 用户修改：修改输出目录以区分不同创新点实验结果
# 功能：将多尺度滑动窗口和MoE实验结果保存到专门的目录，便于对比分析
# 🔥 注意：可通过命令行参数--output_dir覆盖此设置
OUTPUT_DIR: '/home/zubuntu/workspace/yzy/MambaPro/outputs/innovation_experiment' # 创新点实验输出目录

# ========== 创新点使用说明 ==========
# 用户修改：添加详细的使用说明，方便进行消融实验
# 
# 🔥 四种实验组合：
# 1. 基线方法（无创新点）：
#    python tools/train.py --config_file configs/RGBNT201/MambaPro.yml --disable_moe
# 
# 2. 仅多尺度滑动窗口：
#    python tools/train.py --config_file configs/RGBNT201/MambaPro.yml --disable_moe MODEL.USE_CLIP_MULTI_SCALE True
# 
# 3. 多尺度滑动窗口 + MoE融合：
#    python tools/train.py --config_file configs/RGBNT201/MambaPro.yml --use_moe
# 
# 4. 仅MoE融合（不推荐）：
#    python tools/train.py --config_file configs/RGBNT201/MambaPro.yml --use_moe MODEL.USE_CLIP_MULTI_SCALE False
# 
# 🔥 命令行参数优先级：
#    --disable_moe > --use_moe > 配置文件设置
# 
# 🔥 配置文件直接修改：
#    修改 USE_CLIP_MULTI_SCALE: True/False 控制多尺度滑动窗口
#    修改 USE_MULTI_SCALE_MOE: True/False 控制MoE融合
# 
# 🔥 消融实验建议：
#    建议按顺序进行：基线 → 多尺度 → MoE，分析每个创新点的贡献度


